version: '3'
services:
  app:
    build: .
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development